---
- name: "K8S Common - Kinds - Debug Informations"
  ansible.builtin.debug:
    msg:
      - k8s_common.kinds: "{{ k8s_common.kinds | default('') }}"
    verbosity: "{{ os_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_kinds
    - k8s_common_kinds_debug

- name: "K8S Common - Kinds - Manage"
  ansible.builtin.include_tasks: kind.yml
  loop: "{{ k8s_common.kinds | default([], true) }}"
  loop_control:
    loop_var: kind
    pause: "{{ k8s_common.k8s.wait_timeout | default(60) }}"
  when:
    - k8s_common_kinds_manage  | default(true)
    - k8s_common.kinds
  delegate_to: localhost
  tags:
    - k8s_common
    - k8s_common_kinds
    - k8s_common_kinds_manage

...
