---
- name: "K8S Common - Kinds - Debug Informations - Kind : {{ kind.kind | default('') }}"
  ansible.builtin.debug:
    msg:
      - kind: "{{ kind | default('') }}"
    verbosity: "{{ os_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_kinds
    - k8s_common_kinds_debug

- name: "K8S Common - Kinds - Manage - Kind : {{ kind.kind | default('') }}"
  ansible.builtin.debug:
    msg:
      - kind: "{{ kind.kind }}"
      - api_version: "{{ kind.api_version | default(omit) }}"
      - name: "{{ kind.name | default(omit) }}"
      - state: "{{ kind.state | default(omit) }}"
      - context: "{{ kind.state | default(omit) }}"
      - kubeconfig: "{{ kind.kubeconfig | default(k8s_common_kubeconfig.file) }}"
      - wait: true
      - wait_timeout: "{{ wait_timeout_provisioning }}"
  when:
    - kind.manage  | default(true)
    - kind.kind
  delegate_to: localhost
  tags:
    - k8s_common
    - k8s_common_kinds
    - k8s_common_kinds_manage

# - name: "K8S Common - Kinds - Manage - Kind : {{ kind.kind | default('') }}"
#   kubernetes.core.k8s:
#     kind: "{{ kind.kind }}"
#     api_version: "{{ kind.api_version | default(omit) }}"
#     name: "{{ kind.name | default(omit) }}"
#     state: "{{ kind.state | default(omit) }}"
#     context: "{{ kind.state | default(omit) }}"
#     kubeconfig: "{{ kind.kubeconfig | default(k8s_common_kubeconfig.file) }}"
#     wait: true
#     wait_timeout: "{{ wait_timeout_provisioning }}"
#   when:
#     - kind.manage  | default(true)
#     - kind.kind
#   delegate_to: localhost
#   tags:
#     - k8s_common
#     - k8s_common_kinds
#     - k8s_common_kinds_manage

...
