---
- name: "K8S Common - Kinds - Debug Informations - Kind : {{ kind.kind | default('') }}"
  ansible.builtin.debug:
    msg:
      - k8s_common.kinds: "{{ k8s_common.kinds | default('') }}"
    verbosity: "{{ os_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_kinds
    - k8s_common_kinds_debug

# - name: "K8S Common - Kinds - Manage - Kind : {{ kind.id | default('') }}){{ kind.kind | default('') }}"
#       kubernetes.core.k8s:
#         kind: "{{ kind.kind }}"
#         api_version: "{{ kind.api_version | default(omit) }}"
#         name: "{{ k8s.namespace }}"
#         state: present
#         context: "{{ k8s.context }}"
#         kubeconfig: "/tmp/kubeconfig.yml"
#         wait: yes
#         wait_timeout: "{{ wait_timeout_provisioning }}"
#   when:
#     - kind.manage  | default(true)
#     - kind.kind
#   delegate_to: localhost
#   tags:
#     - k8s_common
#     - k8s_common_kinds
#     - k8s_common_kinds_manage

...
