---
- name: "K8S Common - Kubeconfig - Debug Informations"
  ansible.builtin.debug:
    msg:
      - k8s_common_kubeconfig: "{{ k8s_common_kubeconfig | default('') }}"
    verbosity: "{{ os_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_kubeconfig
    - k8s_common_kubeconfig_debug

- name: "K8S Common - Kubeconfig - Check"
  local_action: 
    module: ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: "{{ k8s_common_kubeconfig.file }}"
    mode: "0600"
  tags:
    - k8s_common
    - k8s_common_kubeconfig
    - k8s_common_kubeconfig_check

...
