---
# tasks file for k8s_common

# Loading OS correct vars
- name: "K8S Common - Vars - Load"
  ansible.builtin.import_tasks: load_vars.yml
  tags:
    - k8s_common
    - k8s_common_vars
    - k8s_common_vars_load

- name: "K8S Common - Vars - Print Informations"
  ansible.builtin.debug:
    msg:
      - "ansible_os_family: {{ ansible_os_family | default('') }}"
      - "ansible_distribution: {{ ansible_distribution | default('') }}"
      - "ansible_distribution_release: {{ ansible_distribution_release | default('') }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version | default('') }}"
      - "ansible_distribution_version: {{ ansible_distribution_version | default('') }}"
      - "ansible_pkg_mgr: {{ ansible_pkg_mgr | default('') }}"
    verbosity: "{{ k8s_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_vars
    - k8s_common_vars_debug

# Run Tasks.
- name: "K8S Common - Manage kubeconfig"
  ansible.builtin.import_tasks: kubeconfig.yml
  tags:
    - k8s_common
    - k8s_common_kubeconfig

...
