---
- name: "K8S Common - registries - Debug Informations - Registry : {{ registry }}"
  ansible.builtin.debug:
    msg:
      - registry: "{{ registry | default('') }}"
    verbosity: "{{ k8s_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registry
    - k8s_common_registry_debug

- name: "K8S Common - registries - Manage - Registry : {{ registry }}"
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: "{{ k8s_common_kubeconfig.file }}"
    mode: "0600"
  delegate_to: localhost
  vars:
    dockerconfigjson_auth: "{{ registry.login ~ ':' ~ registry.password }}"
    dockerconfigjson_auth_b64: "{{ dockerconfigjson_auth | b64encode }}"
    dockerconfigjson: "{ \"auths\" :{\"{{ registry.url }}\":{\"username\":\"{{ registry.login }}\",\"password\":\"{{ registry.password }}\",\"email\":\"{{ registry.login }}\",\"auth\":\"{{ dockerconfigjson_auth_b64 }}\"}}}"
    dockerconfigjson_b64: "{{ dockerconfigjson | to_json | b64encode }}" # workaround : using filter to_json to fix simple vs double quote

  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registry
    - k8s_common_registry_manage

...
