---
- name: "K8S Common - Registries - Debug Informations"
  ansible.builtin.debug:
    msg:
      - k8s_common_registries: "{{ k8s_common_registries | default('') }}"
    verbosity: "{{ k8s_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registries_debug

- name: "K8S Common - Registries - Manage"
  ansible.builtin.include_tasks: registry.yml
  loop: "{{ k8s_common_registries | default([], true) }}"
  loop_control:
    loop_var: registry
  when:
    - k8s_common_registries_manage | default(true)
    - k8s_common_registries is defined
  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registries_manage

...
