---
- name: "K8S Common - registries - Debug Informations - Registry : {{ registry }}"
  ansible.builtin.debug:
    msg:
      - registry: "{{ registry | default('') }}"
    verbosity: "{{ k8s_common_debug_level | default(1) }}"
  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registry
    - k8s_common_registry_debug

- name: "K8S Common - registries - Manage - Registry : {{ registry }}"
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: "{{ k8s_common_kubeconfig.file }}"
    mode: "0600"
  delegate_to: localhost
  tags:
    - k8s_common
    - k8s_common_registries
    - k8s_common_registry
    - k8s_common_registry_manage

...
